version: '2'
services:
  ## Common service configuration
  buildkite:
    build:
      context: agents
    environment:
      BUILDKITE_AGENT_NAME: '%hostname'
      BUILDKITE_BUILD_PATH: '/buildkite'
      BUILDKITE_NO_PLUGINS: 'true'
      BUILDKITE_AGENT_NO_LOCAL_HOOKS: 'true'
      BUILDKITE_TIMEOUT: 14400
    env_file:
      - agents/secrets.env
    volumes:
      - /srv/buildkite/cache:/buildkite/cache

  ## Buildkite pipeline agent
  buildkite-pipeline:
    extends: buildkite
    hostname: pipeline-builder
    build:
      args:
        IMAGE: ubuntu

  ## Buildkite ARM64 agent
  buildkite-arm64:
    extends: buildkite
    hostname: ubuntu-arm64
    environment:
      BUILDKITE_AGENT_TAGS: |-
        native=1,
        ubuntu-aarch64=1,
    build:
      args:
        IMAGE: arm64v8/ubuntu
        TARGET: ubuntu-native-arm64

  ## Buildkite ARMv7 agent
  buildkite-arm32:
    extends: buildkite
    hostname: ubuntu-arm32
    environment:
      BUILDKITE_AGENT_TAGS: |-
        native=1,
        ubuntu-arm=1,
        ubuntu-armhf=1,
    build:
      args:
        IMAGE: arm32v7/ubuntu
        TARGET: ubuntu-native-arm32

  ## Buildkite cross agents
  buildkite-cross1:
    extends: buildkite
    hostname: ubuntu-cross1
    environment:
      BUILDKITE_AGENT_TAGS: |-
        cross=1,
        bootstrap=1,
        ubuntu-aarch64=1,
        ubuntu-arm=1,
        ubuntu-armhf=1,
        ubuntu-mips=1,
        ubuntu-mips64el=1,
        ubuntu-mipsel=1,
        ubuntu-powerpc64le=1,
        ubuntu-systemz=1,
        ubuntu-sparc64=1,
        ubuntu-x86_64=1
    build:
      args:
        IMAGE: ubuntu
        TARGET: ubuntu-cross-all

  buildkite-cross2:
    extends: buildkite-cross1
    hostname: ubuntu-cross2
